# Generated by Django 4.1 on 2022-08-31 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kishan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=100)),
                ('animal_leg', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_age', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_salary',
            field=models.FloatField(default=1.0),
        ),
    ]
